### PR TITLE
adding videos

### PR DESCRIPTION
**Pull request by psmulovics**

### CODE REVIEW

**Review by padraignix — COMMENTED** [review]
Maybe add some centering for the braintrust video if not embedding to the column (like the home page video addition.

**Comment by psmulovics** [comment]
> Maybe add some centering for the braintrust video if not embedding to the column (like the home page video addition).

good idea, how does it look now?

**Review by padraignix — COMMENTED** [review]
I like it, but some spacing issues resulting in the header being shifted.

image

**Comment by padraignix** [comment]
Also, looks like the sidebar clips into the video as-is

image

**Comment by psmulovics** [comment]
Ok, this is next week's fixes :D

**Review by padraignix — APPROVED** [review]
Video alignment is better from previous comments/discussion. Approving.

**Pull request merged**
